#ifndef DEVICE_CONFIG_H
#define DEVICE_CONFIG_H

/* MACROS TO TURN IP INTS INTO STRING */
#define XSTR(s) #s
#define STR(s) XSTR(s)

/* MAC ADDRESS*/
#define MAC_ADDR0   02
#define MAC_ADDR1   00
#define MAC_ADDR2   00
#define MAC_ADDR3   00
#define MAC_ADDR4   00
#define MAC_ADDR5   00

/* STATIC IP ADDRESS*/
#define IP_ADDR0   192
#define IP_ADDR1   168
#define IP_ADDR2   1
#define IP_ADDR3   99

/* NETMASK */
#define NETMASK_ADDR0   255
#define NETMASK_ADDR1   255
#define NETMASK_ADDR2   255
#define NETMASK_ADDR3   0

/* GATEWAY ADDRESS */
#define GW_ADDR0   192
#define GW_ADDR1   168
#define GW_ADDR2   1
#define GW_ADDR3   100


/* ROS NODE IDENTIFIER FOR THIS DEVICE */
#define ROS_NODE_UNIQUE_ID "D32"

/* ADDRESS OF ROS MASTER (ROSCORE) */
#define ROS_MASTER_IP_ADDR0   192
#define ROS_MASTER_IP_ADDR1   168
#define ROS_MASTER_IP_ADDR2   1
#define ROS_MASTER_IP_ADDR3   100
#define SERVER_PORT_NUM 11311

/* ADDRESS OF REMOTE LOG DEVICE */
#define LOG_LOCAL_PORT 32005
#define LOG_REMOTE_PORT 32006
#define LOG_REMOTE_IP "192.168.1.100"

#define IP_ADDR STR(IP_ADDR0)"."\
STR(IP_ADDR1)"."\
STR(IP_ADDR2)"."\
STR(IP_ADDR3)
#define ROS_MASTER_IP STR(ROS_MASTER_IP_ADDR0)"."\
STR(ROS_MASTER_IP_ADDR1)"."\
STR(ROS_MASTER_IP_ADDR2)"."\
STR(ROS_MASTER_IP_ADDR3)

#endif

