#ifndef DEVICE_CONFIG_H
#define DEVICE_CONFIG_H

/* MACROS TO TURN IP INTS INTO STRING */
#define XSTR(s) #s
#define STR(s) XSTR(s)

/* ADDRESS OF THIS DEVICE */
#define THIS_REMOTE_IP_ADDR0   192
#define THIS_REMOTE_IP_ADDR1   168
#define THIS_REMOTE_IP_ADDR2   1
#define THIS_REMOTE_IP_ADDR3   99

/* MAC ADDRESS OF THIS DEVICE*/
#define MAC_ADDR0   02
#define MAC_ADDR1   00
#define MAC_ADDR2   00
#define MAC_ADDR3   00
#define MAC_ADDR4   00
#define MAC_ADDR5   00

/* ROS NODE IDENTIFIER FOR THIS DEVICE */
#define ROS_NODE_UNIQUE_ID "D32"

/* ADDRESS OF ROS MASTER (ROSCORE) */
#define ROS_MASTER_IP_ADDR0   192
#define ROS_MASTER_IP_ADDR1   168
#define ROS_MASTER_IP_ADDR2   1
#define ROS_MASTER_IP_ADDR3   100
#define SERVER_PORT_NUM 11311

#define THIS_REMOTE_IP STR(THIS_REMOTE_IP_ADDR0)"."\
STR(THIS_REMOTE_IP_ADDR1)"."\
STR(THIS_REMOTE_IP_ADDR2)"."\
STR(THIS_REMOTE_IP_ADDR3)
#define ROS_MASTER_IP STR(ROS_MASTER_IP_ADDR0)"."\
STR(ROS_MASTER_IP_ADDR1)"."\
STR(ROS_MASTER_IP_ADDR2)"."\
STR(ROS_MASTER_IP_ADDR3)

/* ADDRESS OF REMOTE LOG DEVICE */
#define LOG_REMOTE_IP ROS_MASTER_IP
#define LOG_LOCAL_PORT 32005
#define LOG_REMOTE_PORT 32006

#endif
